name: permission test workflow

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    environment:
      name: prd
    steps:
      - name: env
        run : |
          sleep 5m
          env
