name: test2 workflow

on:
  workflow_dispatch:
    inputs:
      hoge:
        type: string

jobs:
  main:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: env
        env:
          HOGE: ${{ github.event.inputs.hoge }}
        run: |
          echo ${HOGE}
          sleep 5m
          env
